### ISSUE TITLE
I try this package and found issues.

### ISSUE THREAD

**Issue by Racot007** [EmreDogann/unity-guid-reference#4]
1. 1,2 In the dropdown only show types. Would be nice to show the game object name before type (see 3 on the attached pic).
2. In Ref1 scene I set ref to Consumable from scene Ref2 in editor and unload Ref2 scene. After  begin Play and wait 2 seconds I load Ref2 scene with Additive mode but Consumable.Component/Consumable.GameObject is null and field has warning.

![image](https://github.com/EmreDogann/unity-guid-reference/assets/6072592/07d003aa-f617-40a2-b70a-e03cdf9b7038)

**Comment by EmreDogann** [comment]
Hey! Thanks for reporting these! I've made a few changes in 1.0.6

1. I agree that in order to stay more consistent with the default Editor behaviour, the object field should also list the parent GameObject names. I've changed it to match the default unity object field label layout (i.e. GameObject (ComponentType)).
2. I've fixed this bug. You should now be able to unload the scene in editor, and then load the scene additively at runtime without the .Component/.GameObject fields being null.

Please try it out and let me know if it solves your issues :)

**Comment by EmreDogann** [comment]
I will close this issue for now. If the new changes haven't fixed your issues, we can reopen.
